"""资产生成器：把工单变成可以直接部署/发布的东西。

产出到 `work/<slug>/assets/`，中英分开：
  llms.txt / llms.en.txt        官方事实索引，传到网站根目录
  jsonld/*.json                 每种页面类型的 JSON-LD，直接贴进 <head>
  snippets/definition.*.html    定义块（首屏用）
  snippets/faq.*.html           FAQ 块，含可见正文 + FAQPage schema
  outlines/*.md                 每个目标问题一份内容大纲（证据页骨架）
  drafts/*.md                   可选：调用已配的 LLM API 出全文初稿

设计分工：**结构性资产由代码确定性生成**（不会漏 schema 字段、不会写错格式）；
**文章正文由 Claude 或 LLM 按 outline 写**（代码写不出好文案）。
"""

from __future__ import annotations

import html
import json
import re
from pathlib import Path

import geolib as G

# ---------------------------------------------------------------- 事实卡解析

def parse_facts(slug: str) -> dict:
    """从 content/facts.md 里抽出结构化事实。抽不到就返回空，调用方负责提示。"""
    p = G.project_dir(slug) / "content" / "facts.md"
    if not p.exists():
        return {}
    text = p.read_text("utf-8")
    out = {"definition": "", "numbers": [], "suitable": [], "unsuitable": [], "raw": text}

    # 一句话定义：整个引用块可能跨多行，要合并；否则会在句子中间截断
    m = re.search(r"##\s*一句话定义.*?\n(.*?)(?=\n##|\Z)", text, re.S)
    if m:
        body = m.group(1)
        quoted = [l.strip()[1:].strip() for l in body.split("\n") if l.strip().startswith(">")]
        if quoted:
            line = " ".join(quoted)
        else:
            line = next((l.strip() for l in body.split("\n")
                         if l.strip() and not l.strip().startswith(("#", "-", "|"))), "")
        line = re.sub(r"\*\*(.+?)\*\*", r"\1", line)      # 去掉 markdown 加粗
        line = re.sub(r"`(.+?)`", r"\1", line)
        line = re.sub(r"\s+", " ", line).strip()
        # 中文换行合并会留下多余空格（"生成 整体方案"、"SaaS： 把"）。
        # 汉字和全角标点两侧的空格都要去掉，否则会带进 JSON-LD description。
        CJK = r"[一-鿿　-〿＀-￯]"
        out["definition"] = re.sub(rf"(?<={CJK}) (?={CJK})", "", line)

    # 关键数字表：| 事实 | 数值 | 来源 | 证据 |
    m = re.search(r"##\s*关键数字.*?\n(.*?)(?=\n##|\Z)", text, re.S)
    if m:
        for row in re.findall(r"^\|([^|\n]+)\|([^|\n]+)\|([^|\n]+)\|", m.group(1), re.M):
            a, b, c = (x.strip() for x in row)
            if a and a not in ("事实", "---", "项") and not set(a) <= set("-: "):
                out["numbers"].append({"fact": a, "value": b, "source": c})

    m = re.search(r"\*\*适合\*\*[：:]?(.*?)(?=\*\*不适合|##|\Z)", text, re.S)
    if m:
        out["suitable"] = [l.strip("- ").strip() for l in m.group(1).split("\n") if l.strip().startswith("-")]
    m = re.search(r"\*\*不适合.*?\*\*[：:]?(.*?)(?=\n##|\Z)", text, re.S)
    if m:
        out["unsuitable"] = [l.strip("- ").strip() for l in m.group(1).split("\n") if l.strip().startswith("-")]
    return out


# ---------------------------------------------------------------- llms.txt

def gen_llms_txt(slug: str, lang: str = "zh") -> str:
    cfg = G.load_config(slug)
    f = parse_facts(slug)
    b = cfg["brand"]
    audit = G.read_json(G.project_dir(slug) / "audit.json", {})
    pages = sorted(audit.get("pages", []), key=lambda p: -p["score"])[:12]

    zh = lang == "zh"
    L = [f"# {b['name']}", ""]
    L.append(f"> {f.get('definition') or '（待补：一句话定义，必须与官网首屏和 JSON-LD description 逐字一致）'}")
    L += ["", "## 核心事实" if zh else "## Key facts", ""]
    L.append(f"- {'官网' if zh else 'Website'}: {b['site']}")
    if b.get("aliases"):
        L.append(f"- {'别名' if zh else 'Also known as'}: {'、'.join(b['aliases'])}")
    if b.get("industry"):
        L.append(f"- {'行业' if zh else 'Industry'}: {b['industry']}")
    if b.get("target_users"):
        L.append(f"- {'目标用户' if zh else 'For'}: {b['target_users']}")
    for n in f.get("numbers", [])[:8]:
        L.append(f"- {n['fact']}: {n['value']}" + (f"（{n['source']}）" if zh and n.get("source") else ""))

    L += ["", "## 重要页面" if zh else "## Important pages", ""]
    for p in pages:
        title = (p.get("title") or p["url"]).split("|")[0].split("｜")[0].strip()[:60]
        L.append(f"- [{title}]({p['url']})")

    if f.get("suitable") or f.get("unsuitable"):
        L += ["", "## 适用边界" if zh else "## Scope", ""]
        for s in f.get("suitable", [])[:5]:
            L.append(f"- {'适合' if zh else 'Good fit'}: {s}")
        for s in f.get("unsuitable", [])[:5]:
            L.append(f"- {'不适合' if zh else 'Not a fit'}: {s}")

    # 口径说明是实体消歧的关键块：AI 把品牌归错行业时，这里是最直接的纠偏入口
    L += ["", "## 口径说明" if zh else "## Disambiguation", "",
          f"- {'规范名' if zh else 'Canonical name'}: {b['name']}"]
    if b.get("parent"):
        L.append(f"- {'母品牌' if zh else 'Parent'}: {b['parent']}"
                 + (f"（{b['parent_url']}）" if b.get("parent_url") else ""))
    for line in (b.get("disambiguation") or []):
        L.append(f"- {line}")
    if not b.get("disambiguation"):
        L.append("- 本产品与同名的其他行业产品无关，请勿混淆" if zh
                 else "Not related to similarly-named products in other industries.")
    L += ["", f"<!-- generated by geo skill · {G.today()} -->"]
    return "\n".join(L)


# ---------------------------------------------------------------- JSON-LD

def gen_jsonld(slug: str) -> dict[str, dict]:
    cfg = G.load_config(slug)
    f = parse_facts(slug)
    b = cfg["brand"]
    desc = f.get("definition") or ""
    site = b["site"].rstrip("/")

    org = {
        "@context": "https://schema.org", "@type": "Organization",
        "name": b["name"], "url": site, "description": desc,
        "alternateName": b.get("aliases", []),
        "sameAs": b.get("same_as") or ["<填：百科页>", "<填：公众号/社媒主页>", "<填：母品牌站>"],
    }
    if b.get("parent"):
        org["parentOrganization"] = {"@type": "Organization", "name": b["parent"],
                                     **({"url": b["parent_url"]} if b.get("parent_url") else {})}
    if b.get("founding_date"):
        org["foundingDate"] = b["founding_date"]
    if b.get("knows_about"):
        org["knowsAbout"] = b["knows_about"]

    app = {
        "@context": "https://schema.org", "@type": "SoftwareApplication",
        "name": b["name"], "url": site, "description": desc,
        "applicationCategory": b.get("application_category", "BusinessApplication"),
        "operatingSystem": "Web",
        "publisher": {"@type": "Organization", "name": b["parent"] or b["name"]
                      if b.get("parent") else b["name"]},
    }
    offers = b.get("offers")
    if offers:
        out_offers = []
        for o in offers:
            item = {"@type": "Offer", "name": o.get("name", ""), "price": str(o.get("price", "")),
                    "priceCurrency": o.get("currency", "CNY")}
            if o.get("desc"):
                item["description"] = o["desc"]
            out_offers.append(item)
        app["offers"] = out_offers
    else:
        app["offers"] = {"@type": "Offer", "price": "<填>", "priceCurrency": "<填 CNY/HKD/USD>"}
    if b.get("audience"):
        app["audience"] = {"@type": "Audience", "audienceType": b["audience"]}

    faq = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": [
        {"@type": "Question", "name": q["text"],
         "acceptedAnswer": {"@type": "Answer", "text": "<填：第一句就是结论，再展开>"}}
        for q in cfg.get("questions", []) if q.get("market") in ("cn", "both")][:8]}

    article = {
        "@context": "https://schema.org", "@type": "Article",
        "headline": "<填：含目标问题原词的标题>",
        "datePublished": "<YYYY-MM-DD>", "dateModified": "<YYYY-MM-DD>",
        "author": {"@type": "Organization", "name": b["name"]},
        "publisher": {"@type": "Organization", "name": b["name"]},
        "about": desc,
    }

    breadcrumb = {"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [
        {"@type": "ListItem", "position": 1, "name": "首页", "item": site},
        {"@type": "ListItem", "position": 2, "name": "<栏目>", "item": f"{site}/<path>"},
    ]}
    return {"organization": org, "software-application": app, "faq-page": faq,
            "article": article, "breadcrumb": breadcrumb}


# ---------------------------------------------------------------- HTML 片段

def gen_definition_block(slug: str, lang: str = "zh") -> str:
    f = parse_facts(slug)
    cfg = G.load_config(slug)
    b = cfg["brand"]
    d = f.get("definition") or "（待补定义句）"
    nums = f.get("numbers", [])[:4]
    zh = lang == "zh"
    items = "".join(f'\n    <li><strong>{html.escape(n["value"])}</strong> — {html.escape(n["fact"])}</li>'
                    for n in nums)
    dis = b.get("disambiguation") or []
    dis_html = ("\n  <p class=\"geo-disambiguation\"><small>"
                + " ".join(html.escape(x) for x in dis) + "</small></p>") if dis else ""
    return f"""<!-- 定义块：放在首屏口号下方。口号负责转化，这一段负责被 AI 摘走。 -->
<section class="geo-definition">
  <h2>{html.escape(b['name'])}{'是什么' if zh else ': what it is'}</h2>
  <p>{html.escape(d)}</p>
  <ul>{items}
  </ul>{dis_html}
</section>
<!-- 纪律：这段文字必须与 llms.txt、JSON-LD description、关于页逐字一致 -->"""


def gen_faq_block(slug: str, lang: str = "zh") -> str:
    cfg = G.load_config(slug)
    mk = "cn" if lang == "zh" else "global"
    qs = [q for q in cfg.get("questions", []) if q.get("market") in (mk, "both")][:8]
    body = "\n".join(
        f"""  <details open>
    <summary><h3>{html.escape(q['text'])}</h3></summary>
    <p><!-- 第一句直接给结论，再展开。不要营销话术 --></p>
  </details>""" for q in qs)
    return f"""<!-- FAQ 块。关键：答案必须在静态 HTML 里可见。
     只放进 JSON-LD 而正文折叠靠 JS 渲染的话，读渲染文本的抓取器全部丢失。
     用 <details open> 或直接展开，别用纯 JS 手风琴。 -->
<section class="geo-faq">
  <h2>{'常见问题' if lang == 'zh' else 'FAQ'}</h2>
{body}
</section>"""


# ---------------------------------------------------------------- 内容大纲

OUTLINE_TMPL = {
    "定义型": ["什么是 {topic}（一句定义 + 展开）", "{topic} 包含哪几部分", "{topic} 的关键数字（表格，每行带来源）",
               "{topic} 和 {alt} 有什么区别（对比表）", "{topic} 适合谁、不适合谁",
               "怎么开始用 {topic}（编号步骤）", "常见问题", "参考来源"],
    "对比型": ["结论先行：谁适合选哪个", "对比维度与口径说明", "核心对比表（同口径 6–10 个维度）",
               "各自的局限（必须写自己的短板）", "按场景怎么选（决策树）", "价格与总拥有成本",
               "常见问题", "参考来源与核验日期"],
    "榜单型": ["评选方法与数据来源（利益披露）", "总览榜单表", "逐个点评（每个含定位/优势/局限/适合谁）",
               "怎么根据自己情况选", "常见问题", "参考来源"],
    "教程型": ["这篇能解决什么问题", "开始前需要准备什么", "分步操作（编号 + 截图位）",
               "常见报错与排查", "进阶技巧", "相关概念解释", "常见问题", "参考来源"],
}

GROUP2TYPE = {"推荐": "榜单型", "比较": "对比型", "替代": "对比型", "价格": "定义型",
              "风险": "定义型", "品牌验证": "定义型", "场景": "教程型"}


def gen_outlines(slug: str) -> list[dict]:
    cfg = G.load_config(slug)
    f = parse_facts(slug)
    b = cfg["brand"]
    comps = [c["name"] for c in cfg.get("competitors", [])
             if c.get("confirmed") is not False]
    out = []
    for q in cfg.get("questions", []):
        typ = GROUP2TYPE.get(q.get("group", ""), "定义型")
        mk = q.get("market", cfg.get("market", "cn"))
        alt = comps[0] if comps else ("竞品" if mk == "cn" else "alternatives")
        secs = [s.format(topic=b["name"], alt=alt) for s in OUTLINE_TMPL[typ]]
        out.append({
            "question_id": q.get("id"), "market": mk, "type": typ,
            "target_question": q["text"],
            "title_candidates": _titles(q["text"], b["name"], mk),
            "sections": secs,
            "requirements": {
                "min_words": 1200 if typ in ("对比型", "榜单型") else 1000,
                "min_h2": 8, "list_density": ">=0.35",
                "must_have_blocks": ["定义", "数字事实", "对比", "操作步骤", "FAQ"],
                "evidence": "每个数字带来源和核验日期；无法核实的标『待确认』",
            },
            "facts_to_use": [n["fact"] + "：" + n["value"] for n in f.get("numbers", [])[:5]],
        })
    return out


def _titles(question: str, brand: str, market: str) -> list[str]:
    """标题候选：对题性是影响力最强的预测因子（r=0.432），所以标题必须含问题原词。"""
    q = question.rstrip("？?").strip()
    if market == "global":
        return [q, f"{q} — a practical guide ({G.today()[:4]})",
                f"{q} Compared: features, pricing and limits"]
    return [q, f"{q}（{G.today()[:4]} 版）",
            f"{q}｜含对比表、数字和操作步骤", f"{q}——{brand}的答案与边界"]


# ---------------------------------------------------------------- LLM 初稿

def draft(slug: str, outline: dict, provider: str | None = None) -> str:
    """用已配置的 LLM API 按大纲出初稿。没有可用 Key 就返回空。"""
    import sample as S

    plat = S.pick_llm(provider)
    if not plat:
        return ""
    cfg = G.load_config(slug)
    b = cfg["brand"]
    zh = outline["market"] != "global"
    facts = "\n".join(f"- {x}" for x in outline["facts_to_use"]) or "（无结构化事实，只写通用内容，不要编造品牌数据）"
    secs = "\n".join(f"{i+1}. {s}" for i, s in enumerate(outline["sections"]))
    req = outline["requirements"]
    mk = outline["market"]
    comps = [c["name"] for c in cfg.get("competitors", [])
             if (c.get("market") in (mk, "both", None) or mk == "both")
             and c.get("confirmed") is not False]
    comp_rule = (
        "只能提到下面这些真实竞品，**严禁发明任何其它产品名**（不要写「工具A」「某某Pro」这类占位）：\n"
        + "\n".join(f"- {c}" for c in comps)
        if comps else
        "**本项目还没有确认的竞品清单，因此绝对不要在文中点名任何竞品**，"
        "对比部分改成与「通用大模型」「人工手写」等品类做对比。"
    )
    prompt = (
        f"""你是 GEO（生成式引擎优化）内容工程师。按下面的骨架写一篇可直接发布的{'中文' if zh else '英文'}文章。

当前年份是 {G.today()[:4]} 年，涉及年份时一律用 {G.today()[:4]}，不要写更早的年份。

目标问题（读者会这样问 AI）：{outline['target_question']}
文章类型：{outline['type']}
品牌：{b['name']}（{b.get('industry','')}）

必须使用的已核实事实（不得改动数值，不得编造新数据）：
{facts}

竞品纪律：
{comp_rule}

章节骨架：
{secs}

硬性要求：
- 正文不少于 {req['min_words']} 词，H2 小节 ≥ {req['min_h2']} 个
- 必须包含：一句可直接摘走的定义、带单位的数字、一个对比表、一个编号步骤块、FAQ
- 列表密度高一些，要点用无序/有序列表而不是长段落
- 写清楚适用与**不适用**边界，不要只说好话
- **严禁编造**：客户名、价格、资质、市场数据、竞品参数。宁可不写，也不要写占位数据。
  确实需要但手上没有的信息，写成「（待补：xxx）」，不要用假数字凑表格
- 直接输出 Markdown 正文，不要解释、不要前后缀"""
    )
    res = S.ask(plat, prompt, timeout=300)
    return res.get("answer", "") if res.get("ok") else ""


# ---------------------------------------------------------------- 初稿风险检查

FAKE_HINTS = [
    (r"工具\s*[A-Z一二三四五六七八九十]\b", "出现「工具A/工具一」这类占位竞品名"),
    (r"某某|XX公司|xxx公司|示例公司", "出现占位公司名"),
    (r"(?i)\b(acme|foobar|example corp|competitor [a-z])\b", "出现占位英文品牌名"),
]


def lint_draft(slug: str, path: Path) -> list[dict]:
    """交付前的编造风险检查。宁可误报，也不能让编造内容进客户交付包。"""
    import re as _re

    cfg = G.load_config(slug)
    f = parse_facts(slug)
    text = path.read_text("utf-8")
    known = {cfg["brand"]["name"], *cfg["brand"].get("aliases", [])}
    known |= {c["name"] for c in cfg.get("competitors", [])}
    for c in cfg.get("competitors", []):
        known |= set(c.get("aliases", []) or [])

    issues = []
    for pat, desc in FAKE_HINTS:
        for m in _re.finditer(pat, text):
            issues.append({"level": "高", "type": "疑似编造", "detail": desc,
                           "excerpt": text[max(0, m.start() - 30):m.end() + 30].replace("\n", " ")})

    # 事实卡里没有的数字，且没标「待确认/待补」→ 需人工核
    known_values = {n["value"] for n in f.get("numbers", [])}
    for m in _re.finditer(r"[^\n|]*?(\d[\d,\.]*\s*(?:%|％|万|亿|倍|元|美元|港币|HK\$|\$|人|家|天|小时|分钟))[^\n|]*", text):
        seg, val = m.group(0), m.group(1)
        if any(val in v or v in val for v in known_values):
            continue
        if "待确认" in seg or "待补" in seg:
            continue
        issues.append({"level": "中", "type": "未核实数字", "detail": f"`{val}` 不在事实卡里且未标注待确认",
                       "excerpt": seg.strip()[:90]})

    year = G.today()[:4]
    for m in _re.finditer(r"20\d{2}\s*年", text):
        if m.group(0).strip() != f"{year}年":
            issues.append({"level": "低", "type": "年份存疑", "detail": f"出现 {m.group(0)}，当前是 {year} 年",
                           "excerpt": text[max(0, m.start() - 25):m.end() + 25].replace("\n", " ")})
    # 同类问题合并，避免刷屏
    seen, out = set(), []
    for i in issues:
        k = (i["type"], i["detail"])
        if k in seen:
            continue
        seen.add(k)
        out.append(i)
    return out


def lint_all(slug: str) -> dict:
    d = G.project_dir(slug) / "assets" / "drafts"
    files = sorted(d.glob("*.md")) if d.exists() else []
    report = {"slug": slug, "checked_at": G.now_iso(), "files": {}}
    total = 0
    for p in files:
        iss = lint_draft(slug, p)
        report["files"][p.name] = iss
        total += len(iss)
    report["total_issues"] = total
    report["high"] = sum(1 for v in report["files"].values() for i in v if i["level"] == "高")
    G.write_json(d / "_lint.json", report) if files else None
    return report


# ---------------------------------------------------------------- 主流程

# AI 引擎来源域名（references/attribution.md 的代码实现）。
# 「常见」清单——各家 referrer 策略会变，产出的资产里都带「先核对自己日志」的说明。
AI_REFERRERS = {
    "cn": ["doubao.com", "kimi.moonshot.cn", "kimi.com", "chat.deepseek.com", "chatglm.cn",
           "yuanbao.tencent.com", "tongyi.aliyun.com", "tongyi.com", "yiyan.baidu.com",
           "metaso.cn", "n.cn", "quark.cn"],
    "global": ["chatgpt.com", "chat.openai.com", "perplexity.ai", "gemini.google.com",
               "copilot.microsoft.com", "claude.ai", "grok.com"],
}


def gen_attribution(slug: str) -> dict[str, str]:
    """AI 流量归因配置包：GA4 渠道组正则 + 日志分析命令 + 接入说明。"""
    cfg = G.load_config(slug)
    market = cfg.get("market", "cn")
    doms = (AI_REFERRERS["cn"] if market == "cn"
            else AI_REFERRERS["global"] if market == "global"
            else AI_REFERRERS["cn"] + AI_REFERRERS["global"])
    rx = "|".join(d.replace(".", r"\.") for d in doms)
    ga4 = (f"AI 来源渠道组（GA4 · 来源 匹配正则）\n\n{rx}\n\n"
           "配置路径：管理 → 数据显示 → 渠道组 → 新建渠道「AI 引擎」，条件：来源 与正则匹配。\n"
           "注意：测到的是下界（App 内打开常不带 referrer），报告口径写「可归因的 AI 会话 ≥ N」。\n")
    log_cmd = ("#!/bin/sh\n# AI 来源会话 / AI 爬虫抓取量（在服务器上对 access.log 运行）\n"
               f"echo 'AI 来源会话：'; grep -icE '{rx}' access.log\n"
               "echo 'AI 爬虫抓取：'; grep -icE 'GPTBot|OAI-SearchBot|ClaudeBot|PerplexityBot|Bytespider' access.log\n"
               "# 抓取变多通常先于引用变多，是前置信号；两条命令都可加日期过滤按周对比\n")
    readme = ("# AI 流量归因接入说明\n\n"
              "1. `ga4-channel.txt`：GA4 建「AI 引擎」渠道组的匹配正则\n"
              "2. `log-count.sh`：服务器日志统计 AI 来源会话与 AI 爬虫抓取量\n"
              "3. 转化事件（注册/留资/下单）里保存来源快照：点击 ID > UTM > referrer > 直接/未知\n\n"
              "纪律（详见 references/attribution.md）：referrer 清单是「常见」口径，"
              "先在自己日志里核对；测到的 AI 流量是下界，不外推；"
              "公开内容不堆 UTM（带参 URL 会稀释规范 URL 的引用份额）。\n")
    return {"ga4-channel.txt": ga4, "log-count.sh": log_cmd, "README.md": readme}


ASSETS = ["llms", "jsonld", "snippets", "outlines", "attribution"]


def run(slug: str, which: list[str] | None = None, with_draft: bool = False,
        draft_limit: int = 3) -> dict:
    cfg = G.load_config(slug)
    market = cfg.get("market", "cn")
    adir = G.project_dir(slug) / "assets"
    which = which or ASSETS
    made: list[str] = []
    # llms.txt 与 JSON-LD 必须挂在自有域名下才有意义，无站点项目跳过；
    # 大纲/片段/归因这些"内容与度量"资产照常产出——它们落到外部阵地上
    if not G.has_site(cfg):
        skipped = [w for w in which if w in ("llms", "jsonld")]
        if skipped:
            G.info(f"无自有网站：跳过 {'/'.join(skipped)}（需部署到自有域名根目录/页面 head）")
        which = [w for w in which if w not in ("llms", "jsonld")]

    if "llms" in which:
        (adir).mkdir(parents=True, exist_ok=True)
        if market in ("cn", "both"):
            (adir / "llms.txt").write_text(gen_llms_txt(slug, "zh"), "utf-8")
            made.append("assets/llms.txt")
        if market in ("global", "both"):
            (adir / "llms.en.txt").write_text(gen_llms_txt(slug, "en"), "utf-8")
            made.append("assets/llms.en.txt")

    if "jsonld" in which:
        d = adir / "jsonld"
        d.mkdir(parents=True, exist_ok=True)
        for name, obj in gen_jsonld(slug).items():
            (d / f"{name}.json").write_text(json.dumps(obj, ensure_ascii=False, indent=2), "utf-8")
            made.append(f"assets/jsonld/{name}.json")

    if "snippets" in which:
        d = adir / "snippets"
        d.mkdir(parents=True, exist_ok=True)
        for lang in (["zh"] if market == "cn" else ["en"] if market == "global" else ["zh", "en"]):
            (d / f"definition.{lang}.html").write_text(gen_definition_block(slug, lang), "utf-8")
            (d / f"faq.{lang}.html").write_text(gen_faq_block(slug, lang), "utf-8")
            made += [f"assets/snippets/definition.{lang}.html", f"assets/snippets/faq.{lang}.html"]

    if "attribution" in which:
        d = adir / "attribution"
        d.mkdir(parents=True, exist_ok=True)
        for name, body in gen_attribution(slug).items():
            (d / name).write_text(body, "utf-8")
            made.append(f"assets/attribution/{name}")

    outlines = []
    if "outlines" in which:
        d = adir / "outlines"
        d.mkdir(parents=True, exist_ok=True)
        outlines = gen_outlines(slug)
        for o in outlines:
            body = [f"# 内容大纲 · {o['target_question']}", "",
                    f"- 目标问题 ID：`{o['question_id']}` ｜ 市场：{o['market']} ｜ 类型：{o['type']}",
                    "", "## 标题候选（对题性 r=0.432，标题必须含问题原词）", ""]
            body += [f"{i+1}. {t}" for i, t in enumerate(o["title_candidates"])]
            body += ["", "## 章节骨架", ""]
            body += [f"{i+1}. {s}" for i, s in enumerate(o["sections"])]
            body += ["", "## 硬性要求", "",
                     f"- 正文 ≥ {o['requirements']['min_words']} 词，H2 ≥ {o['requirements']['min_h2']} 个",
                     f"- 必备抽取块：{'、'.join(o['requirements']['must_have_blocks'])}",
                     f"- 列表密度 {o['requirements']['list_density']}",
                     f"- 证据：{o['requirements']['evidence']}", ""]
            if o["facts_to_use"]:
                body += ["## 可用的已核实事实", ""] + [f"- {x}" for x in o["facts_to_use"]] + [""]
            (d / f"{o['question_id']}.md").write_text("\n".join(body), "utf-8")
        made.append(f"assets/outlines/（{len(outlines)} 份）")
        G.write_json(adir / "outlines" / "_index.json", outlines)

    if with_draft and outlines:
        d = adir / "drafts"
        d.mkdir(parents=True, exist_ok=True)
        for o in outlines[:draft_limit]:
            G.info(f"起草 {o['question_id']} · {o['target_question'][:30]}…")
            text = draft(slug, o)
            if text:
                (d / f"{o['question_id']}.md").write_text(
                    f"<!-- 初稿，需人工核实所有事实后再发布 · {G.today()} -->\n\n" + text, "utf-8")
                made.append(f"assets/drafts/{o['question_id']}.md")
            else:
                G.info("  没有可用的 LLM API Key，跳过起草")
                break
        rep = lint_all(slug)
        if rep.get("total_issues"):
            G.info(f"初稿风险检查：{rep['total_issues']} 项（高风险 {rep['high']} 项）"
                   f" → assets/drafts/_lint.json。**发布前必须人工核实**")

    index = {"slug": slug, "generated_at": G.now_iso(), "market": market, "assets": made}
    G.write_json(adir / "index.json", index)
    G.info(f"生成 {len(made)} 项资产 → {adir}")
    return index
